In [8]:
import pandas as pd

In [9]:
df2=pd.read_csv("S0_01.17_scores.csv")
df2=df2.sort_values(by="total_score")

In [10]:
df2["total_score"].mean()

-155.2061485148515

In [11]:
df2 = df2[
    (df2["EPI_RMS"] < 0.7) &
    (df2["total_score"] < -155.2)&
    (df2["cav_vol"] <60)
].sort_values(["total_score"],ascending=True)
df2.head(5)

,Unnamed: 0,total_score,BUNS,EPI_RMS,cav_vol,dslf_fa13,fa_atr,fa_dun,fa_elec,fa_intra_rep,...,hbond_bb_sc,hbond_lr_bb,hbond_sc,hbond_sr_bb,omega,p_aa_pp,pro_close,rama,ref,name
43,43,-160.550,12.0,0.684,20.559,-0.798,-331.874,77.607,-41.729,0.551,...,-4.270,-4.926,-13.904,-42.488,9.584,-12.549,0.002,-5.724,-19.341,S0_1.17_44
140,140,-160.361,17.0,0.439,54.551,-0.775,-329.558,82.573,-43.543,0.568,...,-6.049,-4.743,-14.226,-42.480,7.610,-12.369,0.002,-6.424,-20.611,S0_1.17_141
111,111,-160.161,19.0,0.476,25.849,-0.728,-341.113,74.546,-37.511,0.597,...,-4.863,-5.089,-11.125,-41.031,8.096,-11.437,0.014,-4.355,-9.698,S0_1.17_112
179,179,-159.868,15.0,0.381,42.060,-0.712,-341.023,73.820,-44.148,0.538,...,-5.268,-3.394,-16.967,-38.426,8.061,-11.524,0.078,-4.635,-12.170,S0_1.17_180
1,1,-159.860,19.0,0.671,55.719,-0.823,-331.291,83.427,-47.867,0.527,...,-7.048,-3.099,-8.526,-43.604,7.524,-13.766,0.019,-4.059,-23.333,S0_1.17_2